import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {test,expect,jest} from '@jest/globals';
import {createOwnerAuthorityLedger,canonicalAuthorityJson,authorityDigest} from '../../scripts/ao/lib/owner-authority-ledger.js';
import {createOwnerRecoveryPolicy} from '../../scripts/ao/lib/owner-recovery-policy.js';
import {recoverySweep} from '../../scripts/ao/lib/session-recovery.js';
const scope={repository:'Samsen879/ao-pilot',project_id:'ap',task_id:'110',pr_number:123,worker_ref:'worker',session_id:'ap-1',generation:'birth-1',head_sha:'a'.repeat(40),tree_sha:'b'.repeat(40),input_digest:'c'.repeat(64),prior_invocation_id:null};
const secret='unit-fixture-trusted-host';
const sign=canonical=>crypto.createHmac('sha256',secret).update(canonical).digest('hex');
const proof=event=>({signature:sign(canonicalAuthorityJson(event))});
function event(event_id='a',patch={}) {return {schema_version:'ao.owner-authority-event.v1',event_id,kind:'grant',owner_ref:'Owner',source_ref:'owner-message:unit',issued_at:'2026-09-12T00:00:00.000Z',expires_at:'2026-09-14T00:00:00.000Z',scope:{...scope},allowed_actions:['execution.run'],prohibited_actions:[],supersedes:[],revokes:[],dependency_gates:[],...patch};}
async function fixture(run) {const root=fs.mkdtempSync(path.join(os.tmpdir(),'ao-authority-'));const directory=path.join(root,'ledger');let checks=0;
 const options={directory,ownerRef:'Owner',clock:()=>new Date('2026-09-13T00:00:00.000Z'),verifySource:async({canonical,sourceProof})=>{checks++;return sourceProof.signature===sign(canonical)?{owner_ref:'Owner',source_ref:'owner-message:unit'}:null;}};
 const ledger=createOwnerAuthorityLedger(options);try{return await run({root,directory,options,ledger,getChecks:()=>checks});}finally{fs.rmSync(root,{recursive:true,force:true});}}
const ingest=(ledger,e)=>ledger.ingest(e,proof(e));
const consume=(ledger,s=scope,action='execution.run',permit=()=>true)=>ledger.consumeAndPermit({scope:s,action,invocationId:'inv-1'},permit);

test('verifier mandatory: unsigned structural v1 never becomes Owner authority',()=>{expect(()=>createOwnerAuthorityLedger({directory:'/tmp/unit-unused',ownerRef:'Owner'})).toThrow('verifier required');});
test('authenticity is rechecked after restart and exact bytes retained',()=>fixture(async({ledger,directory,options,getChecks})=>{const e=event();await ingest(ledger,e);const bytes=fs.readFileSync(path.join(directory,'a.json'),'utf8');const before=getChecks();await createOwnerAuthorityLedger(options).inspect(scope,'execution.run');expect(getChecks()).toBeGreaterThan(before);expect(fs.readFileSync(path.join(directory,'a.json'),'utf8')).toBe(bytes);expect(await ingest(ledger,e)).toEqual({event_id:'a',duplicate:true});}));
test.each(['signature','owner','scope','digest'])('forged %s holds without permit',kind=>fixture(async({ledger,directory})=>{const e=event();let p=proof(e);if(kind==='signature')p={signature:'forged'};if(kind==='owner')e.owner_ref='Other';if(kind==='scope')e.scope.task_id='different';if(kind==='digest'){await ingest(ledger,e);const file=path.join(directory,'a.json'),env=JSON.parse(fs.readFileSync(file));env.event_sha256='0'.repeat(64);fs.writeFileSync(file,JSON.stringify(env));await expect(consume(ledger)).rejects.toThrow('HOLD');return;}await expect(ledger.ingest(e,p)).rejects.toThrow('HOLD');}));
test('narrow supersession removes broad actions across reopen',()=>fixture(async({ledger,options})=>{await ingest(ledger,event('a',{allowed_actions:['execution.run','conversation.restore']}));await ingest(ledger,event('b',{supersedes:['a'],allowed_actions:[],prohibited_actions:['execution.run']}));await expect(createOwnerAuthorityLedger(options).inspect(scope,'execution.run')).rejects.toThrow('outside');await expect(ledger.inspect(scope,'conversation.restore')).rejects.toThrow('outside');}));
test.each(['expired','revoked'])('%s successor never revives ancestor',kind=>fixture(async({ledger})=>{await ingest(ledger,event());await ingest(ledger,event('b',{supersedes:['a'],expires_at:kind==='expired'?'2026-09-12T01:00:00.000Z':'2026-09-14T00:00:00.000Z'}));if(kind==='revoked')await ingest(ledger,event('r',{kind:'revoke',allowed_actions:[],revokes:['b']}));await expect(consume(ledger)).rejects.toThrow('Expired/revoked');}));
test('incomparable grants and missing/foreign predecessors hold',()=>fixture(async({ledger})=>{await ingest(ledger,event());await expect(ingest(ledger,event('missing',{supersedes:['absent']}))).rejects.toThrow('Missing');await expect(ingest(ledger,event('foreign',{scope:{...scope,task_id:'other'},supersedes:['a']}))).rejects.toThrow('Cross-scope');await ingest(ledger,event('b'));await expect(consume(ledger)).rejects.toThrow('incomparable');}));
test('tampered trusted source replays missing/cyclic reference HOLD',()=>fixture(async({ledger,directory})=>{await ingest(ledger,event());for(const refs of [['absent'],['a']]){const e=event('a',{supersedes:refs});fs.writeFileSync(path.join(directory,'a.json'),JSON.stringify({event:e,source_proof:proof(e),event_sha256:authorityDigest(e)}));await expect(consume(ledger)).rejects.toThrow('HOLD');}}));
test.each(['repository','project_id','task_id','pr_number','worker_ref','session_id','generation','head_sha','tree_sha','input_digest','prior_invocation_id'])('%s must match exact scope',key=>fixture(async({ledger})=>{await ingest(ledger,event());const s={...scope,[key]:key==='pr_number'?124:key==='prior_invocation_id'?'prior':key.endsWith('sha')?'d'.repeat(40):key==='input_digest'?'d'.repeat(64):'different'};await expect(consume(ledger,s)).rejects.toThrow('HOLD');}));
test('rerun consumes only its bound action, cannot widen to restore/merge',()=>fixture(async({ledger})=>{const s={...scope,prior_invocation_id:'previous'};await ingest(ledger,event('rerun',{scope:s,allowed_actions:['execution.rerun']}));await expect(consume(ledger,s,'conversation.restore')).rejects.toThrow('outside');await expect(consume(ledger,s,'merge')).rejects.toThrow('Unsupported');await expect(consume(ledger,s,'execution.run')).rejects.toThrow('mismatch');expect(await consume(ledger,s,'execution.rerun')).toBe(true);}));
test('dependency proof required before receipt and effect',()=>fixture(async({ledger,options,directory})=>{await ingest(ledger,event('g',{dependency_gates:[{gate_id:'design',evidence_sha256:'d'.repeat(64)}]}));const permit=jest.fn();await expect(consume(ledger,scope,'execution.run',permit)).rejects.toThrow('Dependency');expect(permit).not.toHaveBeenCalled();const strict=createOwnerAuthorityLedger({...options,verifyGate:async({gate,proofs})=>proofs.includes(gate.evidence_sha256)});expect(await strict.consumeAndPermit({scope,action:'execution.run',invocationId:'inv-2',gateProofs:['d'.repeat(64)]},()=>fs.readdirSync(path.join(directory,'consumed')).length)).toBe(1);}));
test('receipt durable before permit; permit failure/restart cannot retry',()=>fixture(async({ledger,directory,options})=>{await ingest(ledger,event());await expect(consume(ledger,scope,'execution.run',()=>{expect(fs.readdirSync(path.join(directory,'consumed'))).toHaveLength(1);throw Error('failed effect');})).rejects.toThrow('failed effect');await expect(consume(createOwnerAuthorityLedger(options))).rejects.toThrow('consumed');}));
test('parallel consumption and supersession cannot cross permit lock',()=>fixture(async({ledger})=>{await ingest(ledger,event());let release,entered;const signal=new Promise(r=>entered=r),wait=new Promise(r=>release=r);const one=consume(ledger,scope,'execution.run',async()=>{entered();await wait;return true;});await signal;await expect(consume(ledger)).rejects.toThrow('active');await expect(ingest(ledger,event('b',{supersedes:['a']}))).rejects.toThrow('active');release();expect(await one).toBe(true);await ingest(ledger,event('b',{supersedes:['a']}));}));
test('interrupted lock is not reclaimed',()=>fixture(async({ledger,directory})=>{await ingest(ledger,event());fs.mkdirSync(path.join(directory,'.mutation-lock'),{mode:0o700});await expect(consume(ledger)).rejects.toThrow('interrupted');expect(fs.existsSync(path.join(directory,'.mutation-lock'))).toBe(true);}));
test('truncation and symlink substitution HOLD; no directory creation through symlink',()=>fixture(async({ledger,directory,root,options})=>{await ingest(ledger,event());const file=path.join(directory,'a.json');fs.writeFileSync(file,'{');await expect(consume(ledger)).rejects.toThrow();fs.unlinkSync(file);fs.symlinkSync(path.join(root,'missing'),file);await expect(consume(ledger)).rejects.toThrow();const alias=path.join(root,'alias');fs.symlinkSync(directory,alias);await expect(ingest(createOwnerAuthorityLedger({...options,directory:path.join(alias,'new')}),event())).rejects.toThrow('symlink');expect(fs.existsSync(path.join(directory,'new'))).toBe(false);}));
test('readable-by-others authority custody holds',()=>fixture(async({ledger,directory})=>{await ingest(ledger,event());fs.chmodSync(path.join(directory,'a.json'),0o644);await expect(consume(ledger)).rejects.toThrow('custody');}));

test.each(['absent-policy','running','unknown','wrong-identity','denied','missing-evidence','allowed'])('actual enrolled recovery sweep: %s',kind=>fixture(async({ledger})=>{
 const s={...scope,prior_invocation_id:'previous'},e=event('restore',{scope:s,allowed_actions:kind==='denied'?['execution.rerun']:['conversation.restore']});await ingest(ledger,e);
 const binding={projectId:'ap',conversationId:'conv',authorityEnrollment:{schema_version:'ao.owner-recovery-enrollment.v1',scope:s,invocation_id:'restore-inv',gate_proofs:[]}};
 let live=false;const adapter={validate:async()=>{},alive:async()=>live,restore:jest.fn(async()=>{live=true;})};
 const observer=async(_id,_binding,_scope,permit)=>permit({evidence_status:kind==='missing-evidence'?'missing':'established',state:['running','unknown'].includes(kind)?kind:'interrupted',invocation_id:kind==='wrong-identity'?'foreign':'previous',bound_scope:s});
 const policy=createOwnerRecoveryPolicy({ledger,reconcileExecutionAndPermit:observer});const result=await recoverySweep({sessions:{'ap-1':binding}},adapter,{restore:true,authorityPolicy:kind==='absent-policy'?undefined:policy});
 expect(result.results[0].state).toBe(kind==='allowed'?'RESTORED':'HOLD');expect(adapter.restore).toHaveBeenCalledTimes(kind==='allowed'?1:0);
}));

test('execution starting while source verification waits is rechecked inside restore permit',()=>fixture(async({ledger,options})=>{
 const s={...scope,prior_invocation_id:'previous'};await ingest(ledger,event('race',{scope:s,allowed_actions:['conversation.restore']}));
 let verificationEntered,unblock;const entered=new Promise(r=>verificationEntered=r),barrier=new Promise(r=>unblock=r);
 const blockingLedger=createOwnerAuthorityLedger({...options,verifySource:async args=>{verificationEntered();await barrier;return options.verifySource(args);}});
 let state='interrupted';const restore=jest.fn();const reconciler=jest.fn(async(_id,_binding,_scope,permit)=>permit({state,evidence_status:'established',invocation_id:'previous',bound_scope:s}));
 const policy=createOwnerRecoveryPolicy({ledger:blockingLedger,reconcileExecutionAndPermit:reconciler});
 const binding={projectId:'ap',authorityEnrollment:{schema_version:'ao.owner-recovery-enrollment.v1',scope:s,invocation_id:'restore-race',gate_proofs:[]}};
 const pending=policy.restore('ap-1',binding,restore);await entered;expect(reconciler).not.toHaveBeenCalled();state='running';unblock();
 await expect(pending).rejects.toThrow('not safely terminal');expect(restore).not.toHaveBeenCalled();
}));
