import { sha256Bytes } from './canonical.js';

export const REVIEW_PROTOCOL_VERSION = 'ao.independent-exact-head-body.v1';

const ROLE_MARKERS = [
  /\bindependent(?:ly)?\b[^\n]{0,120}\bexact[- ]head\b/i,
  /\bexact[- ]head\b[^\n]{0,120}\bindependent\b/i,
  /\bsha(?:\/tree)?[- ]bound\b[^\n]{0,120}\bindependent\b/i,
  /\bindependent\b[^\n]{0,120}\bsha(?:\/tree)?[- ]bound\b/i,
  /\bindependent\b[^\n]{0,80}\bfresh[- ]head exact review\b/i,
];
const HEAD_PATTERNS = [
  /reviewed\s+(?:exact\s+github\s+)?head(?:\/tree)?\s*:?\s*`?([0-9a-f]{40})`?/i,
  /reviewed\s+immutable\s+target[^]*?pr\s+head\s*:?\s*`?([0-9a-f]{40})`?/i,
  /(?:pr\s+head|bound\s+(?:to\s+)?head(?:\/tree)?)\s*:?\s*`?([0-9a-f]{40})`?/i,
  /bound\s+(?:only\s+)?to\s+(?:the\s+)?(?:exact\s+)?head\s*`?([0-9a-f]{40})`?/i,
  /bound\s+to\s+commit\s*`?([0-9a-f]{40})`?/i,
  /(?:reviewed\s+)?exact[- ]head(?:\s+review)?(?:\s+of|\s+for|\s+at|\s*[:—–-])?\s*`?([0-9a-f]{40})`?/i,
];
const BLOCKING_SECTION = /^##\s+Blocking findings\s*$/im;
const NUMBERED_FINDING = /^(\d+)\.\s+\*\*([^*\n]+)\*\*([^]*?)(?=^\d+\.\s+\*\*|^##\s+|(?![^]))/gm;
const GENERIC_NUMBERED_FINDING = /^(\d+)\.\s+([^\n]+)([^]*?)(?=^\d+\.\s+|^##\s+|(?![^]))/gm;

const CATEGORY_RULES = Object.freeze([
  ['evidence_custody', /\b(custody|provenance|raw[- ]byte|sha-?256|hash(?:ing)?|authenticated|authentication|source binding|artifact binding)\b/i],
  ['fail_closed_contract', /\b(fail[- ]?open|fail[- ]?closed|must reject|does not reject|fallback|invent(?:s|ed)?|synthesi[sz]e)\b/i],
  ['semantic_authority', /\b(semantic|questionpart|scored route|primary route|procedure|method ownership|canonical output|authority)\b/i],
  ['metrics_truthfulness', /\b(metric|count|denominator|minutes|duration|stale|truthful|reconcile)\b/i],
  ['deterministic_replay', /\b(deterministic|replay|materiali[sz]ed output drift|rebuild|non[- ]determin)\b/i],
  ['test_coverage', /\b(test|fixture|regression|coverage|assertion)\b/i],
  ['scope_boundary', /\b(out[- ]of[- ]scope|scope drift|path escape|allowlist|boundary|external worktree)\b/i],
  ['dependency_contract', /\b(dependency|predecessor|successor|versioned migration|registry entr)\b/i],
]);

const STAGE_RULES = Object.freeze([
  ['task_intake', /\b(task intake|acceptance contract|requirement intake)\b/i],
  ['worker_preflight', /\b(worker preflight|preflight validator|preflight check)\b/i],
  ['ci', /\b(first detectable in ci|ci[- ]detectable|ci gate should)\b/i],
  ['integration', /\b(first detectable at integration|integration gate should)\b/i],
  ['post_merge', /\b(first detected post[- ]merge|post[- ]merge only)\b/i],
]);

function normalizeText(value) {
  return String(value ?? '')
    .replace(/\r\n/g, '\n')
    .replace(/\\n/g, '\n')
    .trim();
}

function protocolVerdict(firstLine) {
  if (/\b(?:NOT PASS|NOT APPROVED|BLOCK(?:ED)?|FAIL(?:ED)?|CHANGES[ _]REQUIRED|CHANGES REQUESTED)\b/i.test(firstLine)) {
    return 'BLOCKED';
  }
  if (/\bPASS\b/i.test(firstLine)) return 'PASS';
  return null;
}

function declaredHead(body, firstLine, roleMarker) {
  for (const pattern of HEAD_PATTERNS) {
    const match = body.match(pattern);
    if (match) return match[1].toLowerCase();
  }
  if (roleMarker) {
    const firstLineSha = firstLine.match(/\b([0-9a-f]{40})\b/i)?.[1];
    if (firstLineSha) return firstLineSha.toLowerCase();
  }
  return null;
}

export function parseIndependentReviewProtocol(review) {
  const body = normalizeText(review?.body);
  const firstLine = body.split('\n')[0].replace(/^\s*[#*]+\s*/, '').trim();
  const protocolPrefix = body.slice(0, 800);
  const roleMarker = ROLE_MARKERS.some((pattern) => pattern.test(protocolPrefix));
  const head = declaredHead(body, firstLine, roleMarker);
  const commitId = String(review?.commit_id ?? '').toLowerCase();
  const verdict = protocolVerdict(firstLine);
  const headBinding = head && /^[a-f0-9]{40}$/.test(commitId)
    ? (head === commitId ? 'exact' : 'mismatch')
    : 'not_established';

  return {
    protocol_version: roleMarker ? REVIEW_PROTOCOL_VERSION : null,
    role_marker: roleMarker,
    verdict,
    declared_head_sha: head,
    commit_id: /^[a-f0-9]{40}$/.test(commitId) ? commitId : null,
    head_binding: headBinding,
    independent_role: roleMarker && headBinding === 'exact',
  };
}

export function isAutomatedInlineSuggestion(comment) {
  const login = String(comment?.user?.login ?? '').toLowerCase();
  const body = normalizeText(comment?.body);
  return (
    login === 'chatgpt-codex-connector[bot]'
    || (login.endsWith('[bot]') && /code review|codex review|p[012] badge|automated review suggestion|generated by/i.test(body))
  );
}

export function isAutomatedActor(value) {
  return String(value?.user?.login ?? value ?? '').toLowerCase().endsWith('[bot]');
}

export function classifyReviewMaterial(review) {
  const protocol = parseIndependentReviewProtocol(review);
  const state = String(review?.state ?? '').toUpperCase();
  const body = normalizeText(review?.body);

  if (protocol.role_marker && protocol.head_binding !== 'exact') {
    return { classification: 'unknown', basis: 'protocol_head_binding_not_exact', protocol };
  }
  if (protocol.independent_role && protocol.verdict === 'BLOCKED') {
    return { classification: 'blocking', basis: 'independent_exact_head_blocked_protocol', protocol };
  }
  if (protocol.independent_role && protocol.verdict === 'PASS') {
    return { classification: 'non_blocking', basis: 'independent_exact_head_pass_protocol', protocol };
  }
  if (state === 'CHANGES_REQUESTED') {
    return { classification: 'blocking', basis: 'github_changes_requested', protocol };
  }
  if (/\b(BLOCK(?:ED)?|FAIL(?:ED)?|NOT APPROVED)\b/i.test(body)) {
    return { classification: 'unknown', basis: 'explicit_blocking_text_without_independent_exact_head_binding', protocol };
  }
  if (body) return { classification: 'unknown', basis: 'unrecognized_review_body', protocol };
  return { classification: 'non_blocking', basis: 'empty_non_blocking_review_submission', protocol };
}

export function classifyCategory(text) {
  for (const [category, pattern] of CATEGORY_RULES) {
    if (pattern.test(text)) return category;
  }
  return 'not_established';
}

export function classifySeverity(text) {
  const match = String(text ?? '').match(/\bP([0-3])\b/i);
  return match ? `P${match[1]}` : 'not_established';
}

export function classifyFirstDetectableStage(text) {
  for (const [stage, pattern] of STAGE_RULES) {
    if (pattern.test(text)) return stage;
  }
  return 'not_established';
}

export function extractBlockingFindings(review) {
  const body = normalizeText(review?.body);
  const sectionMatch = BLOCKING_SECTION.exec(body);
  const informalSection = body.match(/\b(?:actionable|blocking)\s+findings?\b[^:\n]*:/i);
  const numberedStart = body.search(/^1\.\s+/m);
  const section = sectionMatch
    ? body.slice(sectionMatch.index + sectionMatch[0].length)
    : (informalSection
      ? body.slice(informalSection.index + informalSection[0].length)
      : (numberedStart >= 0 ? body.slice(numberedStart) : ''));
  if (!section) {
    const heading = body.match(/^###\s+Blocking finding\s*:\s*(.+)$/im)?.[1];
    if (!heading) return [];
    return [{
      ordinal: 1,
      summary: normalizeText(heading).replace(/[.:]+$/, ''),
      detail: body,
      category: classifyCategory(body),
      severity: classifySeverity(body),
      first_detectable_stage: classifyFirstDetectableStage(body),
      finding_fingerprint: sha256Bytes(Buffer.from(body.replace(/\s+/g, ' ').toLowerCase(), 'utf8')),
    }];
  }
  const findings = [];
  for (const match of section.matchAll(NUMBERED_FINDING)) {
    const ordinal = Number(match[1]);
    const heading = normalizeText(match[2]).replace(/[.:]+$/, '');
    const detail = normalizeText(match[3]);
    findings.push({
      ordinal,
      summary: heading,
      detail,
      category: classifyCategory(`${heading}\n${detail}`),
      severity: classifySeverity(`${heading}\n${detail}`),
      first_detectable_stage: classifyFirstDetectableStage(`${heading}\n${detail}`),
      finding_fingerprint: sha256Bytes(Buffer.from(
        `${heading.toLowerCase()}\n${detail.replace(/\s+/g, ' ').toLowerCase()}`,
        'utf8',
      )),
    });
  }
  if (findings.length === 0) {
    for (const match of section.matchAll(GENERIC_NUMBERED_FINDING)) {
      const ordinal = Number(match[1]);
      const heading = normalizeText(match[2]).replace(/^\*+|\*+$/g, '').replace(/[.:]+$/, '');
      const detail = normalizeText(match[3]);
      findings.push({
        ordinal,
        summary: heading,
        detail,
        category: classifyCategory(`${heading}\n${detail}`),
        severity: classifySeverity(`${heading}\n${detail}`),
        first_detectable_stage: classifyFirstDetectableStage(`${heading}\n${detail}`),
        finding_fingerprint: sha256Bytes(Buffer.from(
          `${heading.toLowerCase()}\n${detail.replace(/\s+/g, ' ').toLowerCase()}`,
          'utf8',
        )),
      });
    }
  }
  return findings.sort((left, right) => left.ordinal - right.ordinal);
}
